### ISSUE TITLE
How to control the chaotic result of spiec-easi？

### ISSUE THREAD

**Issue by wanglu2014** [zdk123/SpiecEasi#103]
Even with same data, the spiec-easi networks have slightly difference.(You can generate one) Each time, when applied different random seed, it will have different network. How can we control the randomness of spiec-easi？
Thank for your help.

**Comment by wanglu2014** [comment]
![图片](https://user-images.githubusercontent.com/12541282/64064089-01ab2280-cc30-11e9-8a38-7a7e55a62270.png)
y-axis is edge number for each different random number calculated network in same data, x-axis is noise added to seperate point for visualization. 
code is ：spiec.out <- spiec.easi(phyloseqobj, method='mb', lambda.min.ratio=1e-2, nlambda=50,pulsar.params = list(seed = 20010))

**Comment by zdk123** [comment]
Well the obvious answer is to set the seed to a single number, as you are doing.

The part of SPIEC-EASI that uses random numbers is the StARS (model selection) where 20 (by default) random 80% subsamples are taken and the graphical model is rebuilt. The resulting models are used to select the penalty parameter. If the final model is not identical, then it's because a slightly different lambda is being selected... perhaps driven by outlier subsamples. To  stabilize the influence of outliers, you can select more than 20 subsamples by setting `rep.num`  to something like 100 or more in the `pulsar.params` list.

**Comment by wanglu2014** [comment]
![图片](https://user-images.githubusercontent.com/12541282/64399975-0abb4a00-d09d-11e9-8de8-ee3f085973c0.png)
Thank for your suggestion!  After looped with fifty random seed, the networks were robust. Except for the slower speed, what is the disadvantage of rep.num 100?

**Comment by zdk123** [comment]
The only disadvantage is the runtime, as you say. 

We try to distribute jobs in embarrassingly parallel mode, so if you could run rep.num=100 with 101 cores  (+1 job for the full dataset), and if you had enough memory, it wouldn't take any longer than a single job. We also have `batch.pulsar` mode, so you could distribute the jobs over an hpc, though that introduces some overhead for passing data back and forth.

**Comment by wanglu2014** [comment]
Your kindly reply always teaches me a deeper understanding of spiec-easi algorithm. Thanks~
