### ISSUE TITLE
Sample name ordering error in multi.spiec.easi

### ISSUE THREAD

**Issue by rozlynboutin** [zdk123/SpiecEasi#114]
Hi,

I am trying to perform a network using 16S and ITS data on the same samples. My 16S and ITS datasets are in separate phyloseq objects and I have sorted them to include only the top 50 most abundant genera in each dataset. I can see that my phyloseq objects have the same number of samples. However, when I run the following code:

se.hmp2 <- spiec.easi(list(top20asv_itsgen, top20asv_bacgen), method='mb', nlambda=40,
                      lambda.min.ratio=1e-2, pulsar.params = list(thresh = 0.1))

I get the error: Error in spiec.easi.list(list(top20asv_itsgen, top20asv_bacgen), method = "mb",  : 
  Do not run multi.spiec.easi with unidentical sample scheme

Is there a way to see what the problem might be? Or to sort the phyloseq objects to make sure the samples appear in the same order?

Thanks in advance!

**Comment by zdk123** [comment]
Currently the sample names vector must be identical, so either the sample names are not consistent or they are not in the same order. 

I agree that sorting samples from within SPIEC-EASI is a reasonable option, but I'd almost rather that users make sure they are in control of the input data structure so that there is no ambiguity in the outputs.

I haven't tried this myself, but the `index_reorder` function in phyloseq should do the trick if it's simply an indexing issue.

**Comment by rozlynboutin** [comment]
Thanks for the quick reply! The index_reorder doesn't seem to work anymore, but the phylosmith package has a set_sample_order function that seems to have done the trick!

**Comment by rozlynboutin** [comment]
Is there a way to know which colour in the visualization goes with which ASV table and to annotate the genera when looking at cross-kingdom interactions?

**Comment by zdk123** [comment]
Great!
If you mean igraph plotting, I suggesting looking at their docs: https://igraph.org/r/doc/plot.common.html There is a lot of customization options, that's outside the scope of support I can provide.
