### ISSUE TITLE
is there a way to avoid very dense networks ?

### ISSUE THREAD

**Issue by Mataivic** [zdk123/SpiecEasi#124]
Hello,

I'm working on a dataset of ~ 600OTUs x 200 samples, and the resulting network is extremely dense (around 3500/4000 edges, everything is connected like an enormous cluster). Is there a way to tune the parameters of SpiecEasi to have a sparser network, or is it fixed by the data itself ? Would it be considerated as "cheating" a bit ? (sorry if the question sounds silly)

I played a bit with the `lambda` and` lambda.min.ratio` parameters for now (mb method), but it did not change the result for now.

Thanks.

**Comment by zdk123** [comment]
`lambda.min.ratio` shouldn't effect the network much but you can select sparser networks by picking a smaller `stars.thresh`. This is effectively choosing a smaller lamba based on an objective criteria (the average stability of network edges over subsamples.)

**Comment by noelzach** [comment]
I think I am having a similar issue and I am trying networks with different stars.thresh. In particular, I was noticing that my networks were coming out with degree distributions that were more normally distributed, rather than resembling a power-law. The degree distributions usually had a mean of about 35-40... this seemed really odd to me. Do you think this is odd as well? Should/could I also think about filtering edges based on the edge stability?

**Comment by zdk123** [comment]
hi @noelzach sorry this slipped out of my inbox. I don't have a good sense of what a target degree distribution should look like. I typically only use edge stability as a ranking criteria but you might get some utility from filtering as well. Note that the resulting network won't satisfy the graphical model selection criteria but if the results look good ...

**Comment by zdk123** [comment]
Agreed w/ @noelzach. Certain community assembly theory would predict power laws but many macroecological networks empirically violate this prediction, which the theory is based on.
