### ISSUE TITLE
Is there a way to run the SpiecEasi faster?

### ISSUE THREAD

**Issue by tcrispino13** [zdk123/SpiecEasi#168]
Hi everyone, I am using the package to run co-occurrence analysis on my sample data( a phyloseq with 201 samples and 8383 ASVs). I ran the program for almost 3 days and then an error occurred, R cannot allocate memory of 263mb. I badly need a way to run the package faster and would not require so much memory. Thanks for your answers!

**Comment by zdk123** [comment]
The surest way is to down-sample your ASVs, perhaps filtering out low-abundant ones but you can also lower any parameter that decreases the number of subsamples (`rep.num`) or evaluates fewer lambdas (`nlambda`)

There are two additional techniques implemented for speed-ups: 

1) The [bounded-StARS](https://github.com/zdk123/SpiecEasi#pulsar-parallel-utilities-for-model-selection) (`bstars` select) which tries to estimate a lower bound for lambda using a limited subsampling scheme and completes subsampling using a restricted lambda path. This should save on memory, and usually saves time if you are CPU-bound but is not usually faster than embarrassingly-parallel mode (e.g. when you can run spiec.easi over each subsample on a separate processor).

2) You can also take a look at the [batch-mode](https://github.com/zdk123/SpiecEasi#batch-mode) option. This will be most useful if you have access to an HPC but since intermediate objects are stored on disk, it can also be useful for memory-bound applications even on a single machine.

**Comment by andrewd789** [comment]
Hi, related to this, is there any way to roughly predict the running time (and memory requirements?), given a certain number of ASVs and other parameters? I have observed the following. With 20 reps, 20 lambda values, 4 cores, and the mb algorithm:
879 ASVs took approximately 1 minute and 1.2 Gb. 
1,679 ASVs took approximately 5 minutes and 2.0 Gb.
2,859 ASVs took over 2 hours and at least 2.6 Gb (didn't complete due to hitting a time limit).

If the processing time is proportional to the number of pairwise comparisons between ASVs, then I would have expected 2,859 to take about 10 minutes, because: 2,859^2 = ~8 million,  which is roughly ten times 879^2 = ~800,000; and 879 ASVs took 1 minute. But 2.879 took much longer than this, so clearly it's not as simple as that. What accounts for the greatly increased processing time?
