### ISSUE TITLE
What does "data normalization/transformation" mean when using with the spiec.easi function?

### ISSUE THREAD

**Issue by dcat4** [zdk123/SpiecEasi#173]
Hi, sorry if I've missed something, but I'm having a tough time figuring out what the spiec.easi function is doing to the raw otu count data prior to the clr transformation and network construction. I've found several issues here about supplying raw counts vs. rarefied counts vs. relative abundances and I understand that the recommendation is to supply the raw count data. As far as I can tell though, there are no details in the documentation or on any of the issue responses that demonstrate what type of data transformation spiec.easi is implementing. I'd like to learn more as I'm hoping to compare networks from (and possibly integrate) some non-sequencing-derived but similarly structured data sets (sparse & compositional) with traditional sequence-data-derived networks.

Could you please elaborate (is it rarefying, normalizing to sample/row sums, etc?) or point me toward some documentation that shows how to perform the clr and network construction without the "default" data transformation employed by spiec.easi?

**Comment by zdk123** [comment]
The CLR transformation with an added pseudo-count is being applied to raw OTU counts prior to network construction. We ask for raw counts since we can't do much data type checking and have to trust the end user is pretty much doing the right thing before applying the network estimation procedure (especially since we're offering a number of other data-determined graphical models now).

However if you don't want SpiecEasi to do the data transformations for you, most of the pipeline is actually implemented in `huge` as well as my other package called [`pulsar`](https://cran.r-project.org/web/packages/pulsar/index.html). This will let you pass in arbitrary data matrices as well as alternative methods for graphical model selection.

Please let me know if that's what you're looking for.

**Comment by dcat4** [comment]
Thank you very much for the response, this is exactly what I was looking for!
