### ISSUE TITLE
Too many Edges! How to handle False Positives?!

### ISSUE THREAD

**Issue by gilienv** [zdk123/SpiecEasi#176]
I'm trying to look at 6000 ASVs across 100 locations. 
SPARCC gives me about 1000 edges at 0.3 threshold and I was hoping to get fewer edges with S-E.

Despite trying over fifty combinations tweaking all parameters in dividually and in combination, I get either Zero edges (Lambda Smaller!) or else >50000 edges, never anything in the range of SPARCC. I suspect these are false positives and looked at the TroubleShooting section.

Increasing min.ratio may decrease edge density and I tried doing that - very fine - to no avail.

se <- spiec.easi(lakes_fung, method='mb', lambda.min.ratio=1e-2,nlambda=20, pulsar.params=list(rep.num=50)) gives ZERO 
se <- spiec.easi(lakes_fung, method='mb', lambda.min.ratio=1e-3,nlambda=20, pulsar.params=list(rep.num=50)) gives 50K!

[For most of my 50K edges, the Stability is in the range of 0.049 and the summary spans neatly around the min.ratio - Here's an example (for 0.01):
> se$select$stars$summary
 [1] 0.000000000 0.001800695 0.003413705 0.005029507
 [5] 0.006644361 0.008254460 0.009930206 0.011971249
 [9] 0.014581289 0.017991869 0.021919245 0.025892348
[13] 0.029646828 0.033494388 0.037750051 0.040571657
[17] 0.042793691 0.045176409 0.047558299 0.050571232

I lowered the min.ratio from 0.01 to 0.001;  0.007 gives 50K edges, while 0.008 gives zero/
I tweaked it further to 0.0075 and many others, but still never able to stabilize at a reasonable number of connections.

I've also tried retaining 1e-3 and varying lambda or RepNum (Lowering both -variously upto 5/5 - gives ZERO) - Increasing both - variously upto 50/100 (Individually and in Combination) returns same high number of edges in the range of 40-50K.

What Am I Doing Wrong?!
Have only tried MB as of yet.. don't wish to try GL or SLR till I've sorted MB

**Comment by zdk123** [comment]
Wow that's a lot of work going into parameter tuning!

So to step back a bit, the StARs procedure picks a network at a fixed variability estimate - this is telling you how frequently on _average_ individual edges are appear in networks fit to subsamples. Note that this is pretty different than creating a 'relevance network' from SparCC correlations (i.e. filtering at |0.3|), since by the StARS definition, the magnitude [strength] of the association doesn't enter into it.

The lambda.min.ratio just determines the extrema of the lambda path, so changing this value shouldn't effect sparsity much (ideally, at all but in practice changing lambda.min.ratio does effect the specific values of lambda in path).

You have some options if you want sparser graphs -
The first option is to just to an effect size filter on the network coefficients - similar to what you've done for SPARCC: e.g. for MB method use `getOptBeta` and filter that. However, since the  coefficients are penalized a universal threshold (such as 0.3) will not be meaningful, so you'd have to play around with that value).


If you'd rather an edge-based confidence filter, you can check out the output from `getOptMerge`. This give edge-wise variability estimates under the subsamples, between [0,1] indicating the proportion of subsampled datasets the edge appeared in. I've used this in a past and, and have had good results using around an 80% filter. This number is something more akin to the empirical p-values that SparCC uses.


A related parameter is the `thresh` argument to `pulsar.params`. This is set to 0.05 (a 5% variability cutoff) but lowering this (e.g. to 1%) will also sparsify the graph in a principled way. You actually don't even need to rerun spiec.easi to change this parameter (in standard stars mode), since all it does is pick an index by inspecting `se$select$stars$summary`.  In this case you could simple change the optimum index to to 7 instead of 19 (based on what you posted).

Hope this helps!

**Comment by gilienv** [comment]
Dear Zach, 

This is VERY helpful, So I'd like to try the edge-based confidence filter, as suggested by you:

sebeta <- symBeta(getOptBeta(se), mode='maxabs')         # For Edge weights
semerge <- getOptMerge(se)                 # For Confidence

Comparing the two matrices above, I notice that sebeta is ALREADY filtered - for weights ONLY for semerge > 70%

The two matrces looks like this (head only):

>sebeta[1:5,1:5]
5 x 5 sparse Matrix of class "dsCMatrix"
                                   
[1,] .         .          0.31697733 .         .
[2,] .         .          0.03389395 0.1092480 .
[3,] 0.3169773 0.03389395 .          0.1200209 .
[4,] .         0.10924803 0.12002086 .         .
[5,] .         .          .          .         .

> semerge[1:5,1:5]
5 x 5 sparse Matrix of class "dgCMatrix"
                             
[1,] .    0.27 1.00 0.28 0.01
[2,] 0.27 .    0.83 0.74 .   
[3,] 1.00 0.83 .    0.97 0.39
[4,] 0.28 0.74 0.97 .    0.08
[5,] 0.01 .    0.39 0.08 .   

------
As you can see, sebeta already gives a filtered output, and with 50K edges in sebeta just now, how do I make it sparser?
Is this what you meant when you suggested the Confidence Filter?

Thanks

**Comment by zdk123** [comment]
sebeta are the [penalized] model coefficients fit from the full dataset.  Non-edges get set to zero due to the penalization but they aren't additionally filtered from the network you already have.
To further filter you could do something like:
`sebeta_filt <- sebeta[abs(sebeta)>0.1]`
or whatever threshold makes sense.


The semerge represents edge weights across all, subsamples, so that would include weights on edges that are not present in the full dataset (and just eyeballing, its not too suprising that edges that are not in the full network (e.g. edge (1,2)) have a smaller confidence than edges that do end up in the full dataset.

Filtering would be a two step process:
1. Get network and 'attach' weights
2. Filter
```r
senet <- getRefit(se) * semerge
semerge_filt <- senet[senet >= 0.8] # or some higher value
```

**Comment by gilienv** [comment]
Thank you Zach! 

The filtering worked perfectly - At 95% confidence, I got a reasonably comparable number of edges - with SPARCC. 

Then I looked at both networks - The communities are clearer and tighter in SE.
I think SE does do a better job than SparcC alone -

<img width="1115" alt="Screenshot 2021-06-27 at 21 12 31" src="https://user-images.githubusercontent.com/20767099/123550947-4866f680-d78d-11eb-9790-03c771e7dd8a.png">

Closing This Issue Now -  Big Thanks!

**Comment by flavien-maucourt** [comment]
Hi Zach, 

I'm trying to do the same thing with my data. I have 3000 OTUs for (only...) 20 samples. the spiec.easi object is calculated as follow : 

spiec.out.phy=spiec.easi(phyloseqobj.f,
                         method="mb", 
                         sel.criterion = 'stars',
                         lambda.min.ratio = 1e-4,
                         nlambda = 30,
                         icov.select.params=list(rep.num=15, ncores=14)
)

I got a good stability of 0.049 and I'm able to plot a very dense graph of this calcul. Because of the previous comments and answers I'd like to try the edge-based confidence filter, as suggested by you. So this is what i did : 

1. Got the spiec.easi object with the previous code 
2. Got the edge-based confidence : 

semerge <- getOptMerge(spiec.out.phy)

3. Do the filtering : 

senet <- getRefit(spiec.out.phy) * semerge
semerge_filt <- senet[senet >= 0.8]

But i got this error : 

<sparse>[ <logic> ] : .M.sub.i.logical() maybe inefficient

So i tried something else : 

semerge <- getOptMerge(spiec.out.phy)>=0.8
senet <- getRefit(spiec.out.phy)*semerge
spiec.graph.phy <- adj2igraph(senet, vertex.attr=list(name=taxa_names(phyloseqobj.f)))
fig <- plot_network(spiec.graph.phy,phyloseqobj.f, type='taxa', color="Domain", label = NA)
fig

I got a grpah :

![image](https://user-images.githubusercontent.com/95645731/146763459-92718cab-b284-4665-857d-542d2ac992ce.png)

But I'm pretty sure that is not correct ! ^^ 

Could you guide me ? 

Last one thing, (If it's not the good place to ask it let me know) these data came from a polluted soil and sample are classified as polluted or not polluted (this is referenced into the metadata of my phyloseq object). How could I sort/plot/read my network based on this information ? 

Thank you in advance for your answer and have a good day.
