### ISSUE TITLE
Retrieving Edge Weights and Labelling Latent Variables with the SLR Method 

### ISSUE THREAD

**Issue by erfanshekarriz** [zdk123/SpiecEasi#193]
Hello, 

I wanted to ask about the newly implemented SLR method with sparse low-rank matrices. Two questions I had specifically. 

1) **How to Obtain Edge Weights**:  What are the equivalents of getOptCov (Glasso) and getOptBeta (MB) for the newly implemented SLR method. I found this line of code on your Synapse Google Drive (analyze_net_funs.R):

getOptSLR <- function(x) {
  ind <- x$ebic>1e-1
  x[ind][[which.min(x$ebic[ind])]]
}
getOpt <- function(x, sign=FALSE) {
  opt <- x
  if (is.null(opt$refit)) {
    opt <- getOptSLR(x)
.
.
.
.

Would this be the correct file to address? 

2) **Using Phyloseq to Label Latent Variables in Hairball Diagrams**: I think the labeling method using Phyloseq is a great visual tool to present your "hairball" diagram. I was wondering how this can also be done to include both taxa and metadata as vertex attributes in the graph network. I can see from your pre-print that you've done this with the Gunandong Microbiome Project and wanted to know about your approach. 

Perhaps a breakdown of the SpiecEasi object produced by the SLR would be greatly helpful in general. 

Many thanks in advanced, 

Erfan SHEKARRIZ

**Comment by zdk123** [comment]
thanks for the request... So actually you wouldn't get metadata covariates in the network via the SLR method but exporting variable labels is something I'm currently working on, as well as integrating 'external' covariates in the way you are requesting.

I'm going to close this issue since both of the requests are being tracked in other issues.
