### ISSUE TITLE
How to correct correlation with sample size?

### ISSUE THREAD

**Issue by wanglu2014** [zdk123/SpiecEasi#194]
Sample size were well known to influence edge weight in correlation network. We plan to construct networks for A (n=152) and B (n=30) groups of samples (human gut microbiome). Do you think we should correct the edge weight in SPIEC-EASI with their different sample size?

**Comment by zdk123** [comment]
I don't have any good theory about sample-size adjusted weighting, but you could use a lower StARS threshold on the network from the smaller sample size (e.g. something like .01 instead of .05) to capture the intuition that we should trust smaller samples less (and thus only looks at edge sets that appear in a larger proportion of subsampled graphs).

**Comment by wanglu2014** [comment]
Thank you for your reply!
