### ISSUE TITLE
Use for time series data?

### ISSUE THREAD

**Issue by adriaaula** [zdk123/SpiecEasi#26]
Hello,

Right now i am working with an amplicon dataset of a whole decade, with a sample for each month. I was interested in apply a network analysis to it, and looking at the literature i found that a possibility would be to use LSA. But I consider the assumptions of SPIEC-EASI more appropiate. There is any problem in using SPIEC with time series data?

The data from my samples is dependent in the sense that they are taken always from the same position. This would modify or affect the covariance effects biasing the results? 

Thank you very much for your time.

**Comment by zdk123** [comment]
It does violate the independent sampling assumption of the Gaussian
graphical model, but if you aren't looking to learn a directed graph and
your sampling is far enough apart, you might be able to get away with it.
One sanity check is to measure autocorrelation (and perhaps
cross-autocorrelation) on the CLR transformed OTU matrix. If these are
close to zero, then you could apply vanilla SPIEC-EASI. Otherwise there are
some other compositionally-robust alternatives that I'd be happy to discuss.
