### ISSUE TITLE
Running spiec.easi with few samples

### ISSUE THREAD

**Issue by mvannuland** [zdk123/SpiecEasi#30]
I am attempting to run spiec.easi with a subset of treatments (n=6) from a larger dataset and am receiving the following error:

"all scheduled cores encountered errors in user codeError in l1[[i]] + l2[[i]] : non-numeric argument to binary operator"

The entire dataset is contained in a phyloseq object, from which I have created new physeq objects by subsetting samples into their respective treatments. Is there a better/different approach that would avoid this error, or is this to be expected with few samples? Thank you!

**Comment by mvannuland** [comment]
Sorry, example of code I run:

ps_control <- subset_samples(physeq_object, Treatment == "Control")

se_ps_control <- spiec.easi(ps_control, method='mb', lambda.min.ratio=1e-3, nlambda=20, icov.select.params=list(rep.num=50, ncores=2))

**Comment by mvannuland** [comment]
And some (non-normalized) data with 6 samples: 
[example_data.txt](https://github.com/zdk123/SpiecEasi/files/1613860/example_data.txt)

**Comment by mvannuland** [comment]
Update:

I subset the amgut example data to 5 samples and could not reproduce the error I am getting. Perhaps there is something about the structure of the OTU table that is causing the error? Subsetting code I ran:

ibd.subset = subset_samples(amgut.ibd, CARBOHYDRATE_PER < 15) #subset down to 5 samples

se.amgut.ibd.sub <- spiec.easi(ibd.subset, method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.params=list(rep.num=20, ncores=nc))

**Comment by zdk123** [comment]
Hi Michael,

   So there are several issues with the input data. I believe the initial
error is a consequence of having a few OTUs that are zeros across all
samples.  Dropping empty OTUs should eliminate the error. In general,
correlations are meaningless with constant data. With only 6 samples, you
will definitely want to limit the number of OTUs in the dataset since the
false positive error will be very high, even with sparsity.

   An additional issue is that StARS procedure subsamples your data at
n_sub=.8*n. With only 6 samples, this means each subsample will be n_sub=5.
6 choose 5 will only give you 6 unique subsamples. Therefore rep.num=20
cannot give you an unbiased estimate of edge stability. Obviously the
treatment group samples have this problem too. This parameter can be
adjusted by setting `stars.subsample.ratio` to a lower number (perhaps 0.5)
but I'm afraid you'll find that most of the detected edges are false
positives anyway.

  You should be able to run the code error-free, but in general I would say
that any network inference procedure is highly suspect with such a small
sample size.

  Please let me know if the error persists.



On Tue, Jan 9, 2018 at 1:18 PM, Michael Van Nuland <notifications@github.com

**Comment by mvannuland** [comment]
Thanks very much for your input. I assume that increasing rep.num wouldn't offer a less-biased estimate of edge stability with such few samples, even if I reduce down to 20ish taxa? Either way, I'll continue to proceed with caution, thanks again!

**Comment by zdk123** [comment]
No... if 6 is the number of total ways you can obtain 5 samples from 6
samples, then only decreasing rep.num << 6 can give you an unbiased sample
in expectation. Then you have the issue that a small rep.num is unlikely to
result in reasonable stability estimates either.

On Tue, Jan 9, 2018 at 2:10 PM, Michael Van Nuland <notifications@github.com

**Comment by mvannuland** [comment]
Ah catch22. I'll explore if I can reasonably pool samples. Thanks for the help!
