### ISSUE TITLE
bstars

### ISSUE THREAD

**Issue by genomewalker** [zdk123/SpiecEasi#40]
Hi 
I've been checking the methods and code from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5571629/ and spiec.easi seems to be using B-StARS as criterion:

```r
se.pos2 <- spiec.easi(pos.filt2, method='mb', sel.criterion='bstars', lambda.min.ratio=2e-2, nlambda=100, pulsar.params=list(rep.num=20, ncores=2))
```
I've been checking the documentation from SpiecEasi and Pulsar but haven't seen any reference. I have a relatively large table (n = 123 ; p = 3676) and I guess that B-StARS will help to reduce the runtime. Is this SpiecEasi branch available? Or do you have any example/recommendation on how to use the B-StARS criterion with SpiecEasi?

Many thanks
Antonio

**Comment by zdk123** [comment]
Hi @genomewalker and thanks for keeping me honest!

I was hesitant to committing the pulsar-related branch to the repo since it includes some API-breaking changes. Then pulsar got temporarily removed from CRAN and I had to fix that first.

[The new branch](https://github.com/zdk123/SpiecEasi/tree/pulsar) should be considered developmental, but exposes a bunch of pulsar goodies for large datasets, especially bstars and batch mode stability selection. For a 3.6k variable dataset, if you have an hpc available, I'd give that a try, since it will allow you to execute all N subsamples in parallel (depending on how forgiving your queuing submission system is). 

I've also added a bunch of getter functions to help parse the output from `spiec.easi`. See the updated README and the help file for ?getOptInd and ?pulsar.params, and please continue to report issues.

Thanks!

**Comment by genomewalker** [comment]
Hi
thank you very much! I already installed it (besides the problem with the remote installation of phyloseq) everything went fine. I will start a job today and let you know how it goes.

**Comment by zdk123** [comment]
thanks! I'll look into that pesky bioconductor issue.
