### ISSUE TITLE
Can SpiecEasi estimate p-values?

### ISSUE THREAD

**Issue by adnbps** [zdk123/SpiecEasi#41]
Is there any way to estimate p-values or q-values for network edges with SpiecEasi? For example, the SparCC package does this with bootstrap resampling. Thanks!

**Comment by zdk123** [comment]
You can get stability estimates for individual edges using the StARS 'merge' matrix. `getOptMerge(se.est)`. This is similar to sparCC's empirical p-values, but uses subsampling, rather than the bootstrap. It's a measure of our confidence that the edge exists, but not of the model coefficients per se. 

Set a large number to `rep.num` in `icov.select.params` to get a large sample estimate.
