### ISSUE TITLE
interpretation of getOptMerge(), and glasso vs. mb methods

### ISSUE THREAD

**Issue by andrewdopheide** [zdk123/SpiecEasi#70]
Hello,

I'm using spiec.easi to infer a cross-domain co-occurrence network, but having some problems interpreting the resulting object:
```
    se.multi <- spiec.easi(otutab_list, method = "mb", 
                                     nlambda = 30, lambda.min.ratio = 1e-4,
                                     sel.criterion ='bstars', pulsar.select = TRUE)
```
Firstly, I check the number of edges with `sum(getRefit(se.multi))/2))` = 66. Then I obtain edge weights. I can't make the example code relating the histogram work; does the following code make sense instead?
```
    se.beta <- as.matrix(symBeta(getOptBeta(se.multi)))
    weights <- se.beta[upper.tri(se.beta) & se.beta!=0]
    length(weights) # 66 (same as number of edges)
```
Secondly, `getOptMerge` is supposed to give symmetric matrix with edge-wise stability, which is something like edge-wise confidence scores, right? But this seems to result in more values than there are edges. So am I misinterpreting what `getOptMerge` does?
```
    sum(getOptMerge(se.multi) > 0)/2) # 307 (vs. 66 edges???)
```
Thirdly, I have some questions about glasso vs. mb (neighbourhood selection) methods. Is there any rule of thumb about when to use one or other of these? Your paper about Spiec-Easi seems to conclude that mb performs better than glasso (yet the default method is glasso?). Would you expect that to always be the case? (I find mb to be much faster than glasso). 

Thanks for any suggestions.

**Comment by zdk123** [comment]
>Secondly, getOptMerge is supposed to give symmetric matrix with edge-wise stability, which is something like edge-wise confidence scores, right? But this seems to result in more values than there are edges.

You're interpretation is correct, but allow be to be more precise, let's say we learn edge (i,j) from  dataset X, which is n x p, given some graphical model method. Then we have a_(i,j) = 1, that is the edge appears in the adjacency matrix at position row i and column j (and vice versa).

What we want to know is p(i,j) - the probability of edge (i,j) given the model. We estimate this empirically by subsampling our data to get \hat{X} which of size n_sub x p, where n_sub is taken to be .8*n, and we generate 20 or so \hat{X}'s.  If edge (i,j) appears in subsample \hat{X}_k, let's represent that as a_k(i,j) = 1. We can now estimate p(i,j) by m_(i,j) = 1\20 [a_1(i,j) + a_2(i,j) + ... a_20(i,j)]  - that is the mean of the edge indicator.

The m_(i,j)'s are what we get out of the `getOptMerge` if we reuse the StARS-selected value of \lambda. What you are missing is that there is no requirement that m_(i,j)=0, even if a_(i,j), since one or more of the subsampled datasets may have the edge, even if the full dataset does not.

**Comment by zdk123** [comment]
Given the sample limit, MB and glasso should be identical since they solve the same objective function. Empirically, we often see neighborhood selection outperform the joint model. Theory can only get us so far, since the data often does not really meet modeling assumptions. It's suggested that required sample complexity scales with the maximum neighborhood size (d) and number of nodes(p) of the graph compare n ~ O(d^2 log(p)) vs n ~ O(d^3 log(p))

https://projecteuclid.org/euclid.aos/1268056617

**Comment by andrewdopheide** [comment]
Thanks for that explanation. So is it correct to say that `getOptMerge()` can contain values for edges that were inferred from one or more subsamples of the dataset, but not from the full dataset? And should I therefore extract only the subset of values returned by `getOptMerge()` that correspond to the set of edges that was inferred from the full dataset?

**Comment by zdk123** [comment]
yes, you could do that.
