### ISSUE TITLE
Comparing structure, stability and stars between networks

### ISSUE THREAD

**Issue by andrewd789** [zdk123/SpiecEasi#77]
Hi, 

I want to compare network structure between different datasets. How should I ensure that SpiecEasi is behaving in a consistent way for each dataset, to maximise comparability? 

One possibility is to use the same SpiecEasi parameters for each dataset. But when I did so, there were differences in the output, perhaps suggesting that I should optimise the parameters in each case. For example, I use these parameters to infer networks from two datasets:
```
se <- spiec.easi(data, method = "mb", nlambda = 30, lambda.min.ratio = 1e-4, 
         sel.criterion ='bstars', pulsar.select = TRUE, pulsar.params = pargs)
```
Output from the first dataset:
```
> se$lambda
 [1] 9.999999e-01 7.278953e-01 5.298316e-01 3.856620e-01 2.807216e-01
 [6] 2.043359e-01 1.487352e-01 1.082637e-01 7.880462e-02 5.736152e-02
[11] 4.175318e-02 3.039195e-02 2.212216e-02 1.610262e-02 1.172102e-02
[16] 8.531678e-03 6.210169e-03 4.520353e-03 3.290344e-03 2.395026e-03
[21] 1.743329e-03 1.268961e-03 9.236708e-04 6.723357e-04 4.893900e-04
[26] 3.562247e-04 2.592944e-04 1.887392e-04 1.373824e-04 9.999999e-05
> se$select$stars$summary
 [1] 1.989222e-05 6.663893e-04 3.917662e-03 8.040324e-03 1.245971e-02
 [6] 3.025673e-02 3.769187e-02 4.403214e-02 4.913906e-02 5.316469e-02
[11] 5.630586e-02 5.883190e-02 6.073164e-02 6.229652e-02 6.365405e-02
[16] 6.487988e-02 6.608207e-02 6.731914e-02 6.864915e-02 7.013505e-02
[21] 7.184895e-02 7.384970e-02 7.619126e-02 7.895624e-02 8.224091e-02
[26] 8.614373e-02 9.074294e-02 5.187227e-02 5.504287e-02 5.841957e-02
> getOptLambda(se)
0.0788046193417128
> getStability(se)
0.0491390628444877
```
Output from the second dataset:
```
>se$lambda
 [1] 1.0000000000 0.7278953844 0.5298316906 0.3856620421 0.2807216204
 [6] 0.2043359718 0.1487352107 0.1082636734 0.0788046282 0.0573615251
[11] 0.0417531894 0.0303919538 0.0221221629 0.0161026203 0.0117210230
[16] 0.0085316785 0.0062101694 0.0045203537 0.0032903446 0.0023950266
[21] 0.0017433288 0.0012689610 0.0009236709 0.0006723358 0.0004893901
[26] 0.0003562248 0.0002592944 0.0001887392 0.0001373824 0.0001000000
>se$select$stars$summary
 [1] 0.03645321 0.03645321 0.03645321 0.03645321 0.03645321 0.03645321
 [7] 0.03645321 0.03645321 0.03645321 0.03645321 0.03645321 0.03645321
[13] 0.03645321 0.03645321 0.03645321 0.03645321 0.03645321 0.03645321
[19] 0.01954147 0.02009200 0.02084605 0.02165781 0.02277525 0.02405644
[25] 0.02570959 0.02783139 0.03033762 0.03342402 0.03671472 0.03988300
>getOptLambda(se)
0.00452035365636025
>getStability(se)
0.0364532129965588
```

Q1: Is the first network "better" than the second, because the stability value is much closer to the 0.05 threshold (0.049 vs. 0.036)? Would it therefore be unwise to compare network structure between the two?

Q2: Why does the stars summary from the second network contain lots of identical values? 

Q3: Can you suggest if/how I should change the parameters for the second dataset, to get a network that is more comparable to the first? 

Thanks for any suggestions.

**Comment by andrewdopheide** [comment]
I am going to answer my own questions. I repeated the second network inference using  ```sel.criterion ='stars'```, instead of ```sel.criterion = 'bstars'```. The result was a range of values (none identical) in the stars summary, and a stability value much closer to 0.05 (0.047 compared to 0.036:
```
>se$select$stars$summary
[1] 0.000000000 0.005273527 0.009729971 0.013825251 0.017632313 0.021101909
 [7] 0.024110222 0.026650809 0.028745016 0.030408382 0.031779960 0.032860679
[13] 0.033782188 0.034589347 0.035330165 0.036049400 0.036773547 0.037590827
[19] 0.038508984 0.039610663 0.040966209 0.042625226 0.044703718 0.047342955
[25] 0.050686624 0.054875664 0.059993800 0.066100974 0.072674625 0.079089812
>getStability(se)
0.0473429549727426
```

To answer Q2, the identical values in the stars summary are evidently due to using the bounded stars selection criteria. 

To answer Q1 and Q3, using stars instead of bounded stars resulted in a closer stability value to 0.05 (and ~ 20 % more edges). I assume this result may therefore be a "better" version of the second network, to compare to the first. 

This prompts another question: why would the bounded stars method not arrive at a similar stability value as the regular stars method?

**Comment by zdk123** [comment]
In bounded StARS, we compute the stability path for N=2 subsets to get a rough estimate of the stability path (`.$select$stars$summary`). This cuts off small values of lambda for the remaining subsamples, and so for a subset of the path, we only are only ever subsampling twice. Hence the identical summary values:
https://arxiv.org/abs/1605.07072

As discussed in our paper, however - and unfortunately - we don't have consistency guarantees, especially for some underlying graph solvers that may use warm starts along the lambda path, non-sparse and low-dimensional graphs, etc.

The odd thing I see in your second dataset is that the stability never rises above `0.039`, and the output to the getter functions don't seem to match up with the lambda / stability paths that immediate proceed it... This is unexpected and if you can share your data / code or outputs, I would be very interested in studying (and hopefully fixing) this pathological case.

**Comment by zdk123** [comment]
To answer your third question, well it really depends on what you mean by comparable. You can also compare a set of nodes and edges using some higher order summary statistics (e.g. via the igraph package). The idea behind StARS is to select a lambda for which the average stability is at a fixed threshold. So if you use the same threshold for two networks, they are comparable in that probabilistic framework.

However, one method that I've used in the pass is to filter/rank edges by the edge-wise stability (the `getOptMerge`) matrix. One could filter so that the number of edges in the networks are identical, or filter to high confident individual edges (e.g. that appear in less than X% of subsamples). But I do not know if any of these filterings would faithfully represent the network topology.

**Comment by andrewdopheide** [comment]
Thanks for the advice. I think the outputs from the getter functions do match up with the preceeding lambda/stability paths, do they not?  They appear to be the 18th values in both the lambda and stability summaries. 

I have observed a number of similar cases, all using bounded StARS, wherein the stability doesn't rise above ~0.035-0.042, also accompanied by identical values (at ~0.036) in the StARS summary. The selected stability value in these cases always appears to be the last of the identical values. The second network above is one such case, and (hopefully) the data that led to this is attached below:

[D9_data.zip](https://github.com/zdk123/SpiecEasi/files/3052259/D9_data.zip)

It contains four tables, which I would load into R using ```read.table(...)```, then transpose so that samples are in the rows, and then combine into a list. I then provide the list to SpeicEasi as follows:
```
pargs <- list(rep.num = 50, seed = 10010, ncores = 4)
se.multi <- spiec.easi(data_list, method = "mb", nlambda = 30, lambda.min.ratio = 1e-4,
                         sel.criterion ='bstars', pulsar.select = TRUE, pulsar.params = pargs)
```

**Comment by zdk123** [comment]
Thanks, this does sound like a bug.

**Comment by andrewdopheide** [comment]
No problem, glad to help. 
Just a (possibly related) extra question: Is there any reason why a decrease in the number of samples included might lead to memory problems? For example, I can typically infer a network based on sets of about 40 samples within a few tens of minutes. But if I subset these data to, say, 15 samples, the network inference often fails due to an apparent memory problem.

**Comment by zdk123** [comment]
Possibly you are seeing the same error we're tracking in #73?

If so this is an Rcpp error that is being fixed in the next `huge` release.

**Comment by andrewdopheide** [comment]
Could be, thanks. I will look forward to a fix!
