### ISSUE TITLE
Error with edges

### ISSUE THREAD

**Issue by davidvilanova** [zdk123/SpiecEasi#91]
Hi ,
While trying to use the glasso method i get the following error. The number of edges returned by getOptCov does not correspond to the number of edges that are found correlated  ???

```
> mb <- spiec.easi(physeq_obj, method='glasso', lambda.min.ratio=lambda,pulsar.params=list(rep.num=20,ncores=cpus))
Applying data transformations...
Selecting model with pulsar using stars...
Fitting final estimate with glasso...
done
> betaMat=as.matrix(getOptCov(mb))
> ig <- adj2igraph(getRefit(mb), diag=T, rmEmptyNodes=TRUE, edge.attr=list(weight=betaMat),vertex.attr=list(name=taxa_names(physeq_obj)))  #show connected nodes
Warning message:
In eattrs[[name]][index] <- value :
  number of items to replace is not a multiple of replacement length


```

Not sure i´m properly getting the weight of the edges ??

**Comment by zdk123** [comment]
Hi @davidvilanova, This is expected behavior: the support (non-zero edges) of an precision matrix is not equal to the support of it's inverse (the covariance matrix).

Try instead:
```diff
- betaMat=as.matrix(getOptCov(mb))
+ betaMat=as.matrix(getOptiCov(mb))
```

Furthermore, since you are using `glasso`, please know that the entries of the are not 'beta' coefficients - that is strictly the case for neighborhood selection (`method="mb"`), but rather an estimate of the precision values directly.

**Comment by davidvilanova** [comment]
Great work !!!!
Thanks
