### ISSUE TITLE
Spiec Easi Tutorial Struggle

### ISSUE THREAD

**Issue by jacquicomstock** [zdk123/SpiecEasi#99]
Hi there,

I am new to R and SpiecEasi, so I recognize that these are likely easily fixable issues, but I'd like to ask.
To start to familiarize myself with the package I tried to copy/paste the entire tutorial verbatim using the amgut data (from here: https://www.rdocumentation.org/packages/SpiecEasi/versions/0.1.4), but ran into errors in multiple places

First, the following line:
huge::huge.roc(se.est$path, graph, verbose=FALSE)

produced the error:
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

Second, after completing the spec.easy pipeline, when attempting to create igraph objects the following lines:
ig.mb <- adj2igraph(se.mb.amgut$refit)
ig.gl <- adj2igraph(se.gl.amgut$refit)

both produced the following error:
Error in mde(x) : (list) object cannot be coerced to type 'double'

Both errors seem to be simple format issues, but since I am not particularly good with R I haven't been able to fix them with a quick little google search. 
 Could anyone help out?

**Comment by zdk123** [comment]
The tutorial at that link is out of date. I introduced some API breaking in version 1 (hence the semantic bump).

You can follow working examples on the README page on this github:
https://github.com/zdk123/SpiecEasi#spieceasi

I think rdocumentation must have pulled from bioconda, since that is hosting on old version as well.

**Comment by jacquicomstock** [comment]
ah perfect, thanks so much for a quick response!
